### ISSUE TITLE
ImportError: No module named xml.etree.ElementTree

### ISSUE THREAD

**Issue by githlp** [pypa/get-pip#101]
Hello,
on BuildRoot environment (MotionEyeOS) i used for the installed Python 2.7.15 following installer script:

`# curl https://bootstrap.pypa.io/2.7/get-pip.py --output get-pip.py
`
But when i run it ..
`# python get-pip.py`
 
Traceback (most recent call last):
  File "get-pip.py", line 23974, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 83, in bootstrap
    from pip._internal.commands.install import InstallCommand
  File "/tmp/tmpAUOKQl/pip.zip/pip/_internal/commands/install.py", line 17, in <module>
  File "/tmp/tmpAUOKQl/pip.zip/pip/_internal/cli/req_command.py", line 18, in <module>
  File "/tmp/tmpAUOKQl/pip.zip/pip/_internal/index/collector.py", line 14, in <module>
  File "/tmp/tmpAUOKQl/pip.zip/pip/_vendor/html5lib/__init__.py", line 25, in <module>
  File "/tmp/tmpAUOKQl/pip.zip/pip/_vendor/html5lib/html5parser.py", line 6, in <module>
  File "/tmp/tmpAUOKQl/pip.zip/pip/_vendor/html5lib/_inputstream.py", line 14, in <module>
  File "/tmp/tmpAUOKQl/pip.zip/pip/_vendor/html5lib/_utils.py", line 18, in <module>
ImportError: No module named xml.etree.ElementTree

**Comment by webknjaz** [comment]
That module is a part of the stdlib since Python 2.5. The inability to import it indicates that you CPython install is incomplete/broken/damaged. This project only works with standard distributions of Python.

**Comment by pradyunsg** [comment]
Closing since OP likely has a failure due to an incomplete build of Python. Feel free to holler if there’s more nuance to this. :)
