### ISSUE TITLE
get-pip.py is not comatible with Python2

### ISSUE THREAD

**Issue by sebma** [pypa/get-pip#11]
Hi,

When I run `./get-pip.py`, here is what I get:

```
~/src/get-pip $ ./get-pip.py 
Traceback (most recent call last):
  File "./get-pip.py", line 20061, in <module>
    main()
  File "./get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "./get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmp38Y8IC/pip.zip/pip/__init__.py", line 26, in <module>
  File "/tmp/tmp38Y8IC/pip.zip/pip/utils/__init__.py", line 27, in <module>
  File "/tmp/tmp38Y8IC/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
  File "/tmp/tmp38Y8IC/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
  File "/tmp/tmp38Y8IC/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
  File "/tmp/tmp38Y8IC/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
  File "/tmp/tmp38Y8IC/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
  File "/tmp/tmp38Y8IC/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2091, in _handle_ns
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
~/src/get-pip $ echo $?
1
```
It seems get-pip.py is not compatible with Python2 anymore.

Can you please change the shebang from `#!/usr/bin/env python` to `#!/usr/bin/env python3` ?

**Comment by sebma** [comment]
Sorry, it seemed that my pkg-resources had been corrupted after a pip --upgrade.

Closing this wrong issue.
