### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.cmd'

### ISSUE THREAD

**Issue by BansheePrime** [pypa/get-pip#124]
pip installation on Debian 11 via get-pip.py
python  3.9.2

```
root@debi:~# python3 get-pip.py
Traceback (most recent call last):
  File "/root/get-pip.py", line 24556, in <module>
    main()
  File "/root/get-pip.py", line 139, in main
    bootstrap(tmpdir=tmpdir)
  File "/root/get-pip.py", line 115, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "/root/get-pip.py", line 96, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/cli/base_command.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/cli/cmdoptions.py", line 23, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/configuration.py", line 27, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/utils/misc.py", line 42, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/locations/__init__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpc1mpf262/pip.zip/pip/_internal/locations/_distutils.py", line 9, in <module>
ModuleNotFoundError: No module named 'distutils.cmd'
```

**Comment by theo-brown** [comment]
Same here

**Comment by franklinscudder** [comment]
Also got this error on Debian 10 Buster, Python 3.7.3.

**Comment by PawelZ-RD** [comment]
Same on Ubuntu 20.04, Python 3.9.5
It used to work fine couple weeks ago...

**Comment by xavfernandez** [comment]
It's likely because you're on a system that does not install the `distutils` module alongside python even though it is still part of the python standard library. `sudo apt-get install python3-distutils` (or something like that) should solve your issue.

**Comment by PawelZ-RD** [comment]
Sadly, on Ubuntu 20.04, `python3-distutils` is Python3.8 package. `python3.9-distutils` is a virtual that installs `python3-distutils`.
The reason I am trying to install `pip` via `get-pip.py` is to have Python3.9 only, with no 3.8.
I seems, I will have to get `distutils` directly from source first (what should be covered in `get-pip.py` IMHO).

Now, I see why it 'worked' before, it was Python 3.8

**Comment by PawelZ-RD** [comment]
After manually adding `distutils`:
```
# python3.9 get-pip.py
Collecting pip
  Downloading pip-21.2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 31.9 MB/s
Collecting setuptools
  Downloading setuptools-57.4.0-py3-none-any.whl (819 kB)
     |████████████████████████████████| 819 kB 37.0 MB/s
Collecting wheel
  Downloading wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-21.2.4 setuptools-57.4.0 wheel-0.37.0

# pip --version
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

# pip3 --version
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

# ls -l /usr/lib/python3.9/site-packages/
total 36
drwxr-xr-x 3 root root 4096 Aug 24 16:40 _distutils_hack
-rw-r--r-- 1 root root  152 Aug 24 16:40 distutils-precedence.pth
drwxr-xr-x 5 root root 4096 Aug 24 16:40 pip
drwxr-xr-x 2 root root 4096 Aug 24 16:40 pip-21.2.4.dist-info
drwxr-xr-x 6 root root 4096 Aug 24 16:40 pkg_resources
drwxr-xr-x 7 root root 4096 Aug 24 16:40 setuptools
drwxr-xr-x 2 root root 4096 Aug 24 16:40 setuptools-57.4.0.dist-info
drwxr-xr-x 5 root root 4096 Aug 24 16:40 wheel
drwxr-xr-x 2 root root 4096 Aug 24 16:40 wheel-0.37.0.dist-info
```

**Comment by pradyunsg** [comment]
Okay, so it's confirmed that this is caused by Debian's patches to Python.

They break out `distutils` from the CPython standard library. Please file a bug with Debian, with `reportbug python3` (per their reporting [documentation](https://www.debian.org/Bugs/Reporting)). You can link to this issue in your bug report.

Closing this, since I don't think we can do anything about this on our end. If someone has ideas, please go ahead and let us know in a new issue. :)

**Comment by edwardnguyen1705** [comment]
> 
Hi @PawelZ-RD ,
Could you tell me, how manually adding distutils?

**Comment by elkd** [comment]
😭 Why Debian, Why Python? Why?

**Comment by ei-grad** [comment]
https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1940705

> Stefano Rivera (stefanor)] on 2022-03-12:
> Fixed in 3.10.2-3.
> Changed in python3.10 (Ubuntu):
> status: 	Confirmed → Fix Released

**Comment by VioPsycho** [comment]
if you get this error
**ModuleNotFoundError: No module named 'distutils.cmd'**

`sudo apt-get install python3.10-distutils`

**Comment by AhmedTremo** [comment]
This solved it for me:

`sudo apt-get install --reinstall python3.7-distutils`

**Comment by pradyunsg** [comment]
Please report this as a bug to Debian and Ubuntu, if it has not been reported already.
