### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by omxpro** [pypa/get-pip#127]
om@localhost:~$ curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
om@localhost:~$ python3 get-pip.py                Traceback (most recent call last):                  File "get-pip.py", line 24556, in <module>          main()
  File "get-pip.py", line 139, in main                bootstrap(tmpdir=tmpdir)                        File "get-pip.py", line 115, in bootstrap
    monkeypatch_for_cert(tmpdir)                    File "get-pip.py", line 96, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand                                         File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>             File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/cli/base_command.py", line 12, in <module>             File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/cli/cmdoptions.py", line 23, in <module>
  File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>                   File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/configuration.py", line 27, in <module>                File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/utils/misc.py", line 42, in <module>                   File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/locations/__init__.py", line 14, in <module>           File "/tmp/tmp78eno5x9/pip.zip/pip/_internal/locations/_distutils.py", line 9, in <module>        ModuleNotFoundError: No module named 'distutils.cmd'                                                om@localhost:~$

**Comment by pradyunsg** [comment]
Are you on Ubuntu?

**Comment by pradyunsg** [comment]
This issue looks like it's caused by changes that Debian made to their Python package. Please file a bug with Debian, with `reportbug python3-pip` (their reporting [documentation](https://www.debian.org/Bugs/Reporting)). You can link to this issue in your bug report.

I believe you can probably solve this by running `apt install python3-venv`.

**Comment by omxpro** [comment]
@fixed ty
