### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by baerrs** [pypa/get-pip#160]
I'm running this on a Windows 10 Home (not my choice of systems)

I'm on a freshly installed Python 3.10.5, customer install (changed the install dir, and did select install for all user, and py).  

I does not install pip (even though it was selected.  
```

`
c:\Users\baerr\test> curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py

c:\Users\baerr\test>python get-pip.py
Traceback (most recent call last):
  File "c:\Users\baerr\test\get-pip.py", line 33593, in <module>
    main()
  File "c:\Users\baerr\test\get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "c:\Users\baerr\test\get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "c:\Users\baerr\test\get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "C:\Users\baerr\AppData\Local\Temp\tmpdxvqx06s\pip.zip\pip\_internal\commands\__init__.py", line 9, in <module>
  File "C:\Users\baerr\AppData\Local\Temp\tmpdxvqx06s\pip.zip\pip\_internal\cli\base_command.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen zipimport>", line 170, in find_spec
  File "<frozen importlib._bootstrap>", line 431, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location
  File "<frozen zipimport>", line 229, in get_filename
  File "<frozen zipimport>", line 752, in _get_module_code
  File "<frozen zipimport>", line 586, in _get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\baerr\\AppData\\Local\\Temp\\tmpdxvqx06s\\pip.zip'

c:\Users\baerr\test>python --version
Python 3.10.5

c:\Users\baerr\test>echo %PATH%

C:\Python310\Scripts\;C:\Python310\;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\WireGuard\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\dotnet\;C:\Program Files\PuTTY\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\baerr\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PhpStorm 2021.2\bin;C:\Program Files (x86)\FAHClient;C:\Program Files (x86)\Nmap;C:\Users\baerr\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.3\bin;C:\Users\baerr\AppData\Local\GitHubDesktop\bi;C:\Users\baerr\AppData\Roaming\npm;c:\users\baerr\.local\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\bin;C:\Users\baerr\AppData\Local\JetBrains\Toolbox\scripts

```

Any help is appreciated!!

Scott

**Comment by pradyunsg** [comment]
This is likely a case of some sort of antivirus program or something deleting the file that pip itself is running via. That's... weird.

It's been a few months since this was filed though, so I hope you were able to figure this out. I'm going to go ahead and eagerly close this, but please feel welcome to comment on this after it's closed with how you investigated/fixed this or to reopen this if it's not resolved and you'd be interested in help to resolve this. :)
