### ISSUE TITLE
#pipa 'get-pip.py' install error 

### ISSUE THREAD

**Issue by honda2017** [pypa/get-pip#166]
root@baozihh-QL9S:/home/baozihh/git_practice# python3 get-pip.py 
Traceback (most recent call last):
  File "get-pip.py", line 32099, in <module>
    main()
  File "get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/cli/base_command.py", line 15, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/configuration.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/utils/logging.py", line 29, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/utils/misc.py", line 42, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/locations/__init__.py", line 67, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpsr0q_xyy/pip.zip/pip/_internal/locations/_distutils.py", line 20, in <module>
ModuleNotFoundError: No module named 'distutils.cmd'
root@baozihh-QL9S:/home/baozihh/git_practice#

**Comment by pradyunsg** [comment]
That looks like a broken Python installation. If you're using Debian-derived OS, `apt-get install python3-distutils` might be what you need here (or python3.x-distutils, replacing x with whatever minor version of Python you're using).

Beyond that, I suggest reporting to Debian's community (their reporting [documentation](https://www.debian.org/Bugs/Reporting) to report that they're shipping a broken distutils. You can link to this issue in your bug report.

Closing this, since I don't think we can do anything about this on our end.

**Comment by honda2017** [comment]
> 
thanks, use  "apt-get install python3-distutils"  fixed it!
