### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.cmd'

### ISSUE THREAD

**Issue by bercedev** [pypa/get-pip#181]
how to fix

```
root@193:~/CerceynUserbot# python3.9 get-pip.py
Traceback (most recent call last):
  File "/root/CerceynUserbot/get-pip.py", line 32275, in <module>
    main()
  File "/root/CerceynUserbot/get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "/root/CerceynUserbot/get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "/root/CerceynUserbot/get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/cli/base_command.py", line 15, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/configuration.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/utils/logging.py", line 29, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/utils/misc.py", line 43, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/locations/__init__.py", line 68, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpm4v9qo22/pip.zip/pip/_internal/locations/_distutils.py", line 20, in <module>
ModuleNotFoundError: No module named 'distutils.cmd'
```

**Comment by bercedev** [comment]
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-57-generic x86_64)

**Comment by pradyunsg** [comment]
You need to install python3-full. Also, report this to Debian/Ubuntu folks please. :)
