### ISSUE TITLE
ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.

### ISSUE THREAD

**Issue by SankaraNarayananK-sudo** [pypa/get-pip#226]
Seeing this issue related to uninstalling the existing pip when try to install the latest pip version available using the below command.

**curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11**

This was working without any issue till 2 weeks back. Hitting this issue recently. I do find some changes went in to get-pip.py related to 24.3.1 from @sbidoul (Stéphane Bidoul). Is it some thing related to that? Could anyone help in this issue please?

cc @edmorley 

```
 > [ 5/20] RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11:
0.333 update-alternatives: using /usr/bin/python3.11 to provide /usr/bin/python3 (python3) in auto mode
0.346 Error processing line 1 of /usr/lib/python3/dist-packages/distutils-precedence.pth:
0.346
0.357   Traceback (most recent call last):
0.357     File "<frozen site>", line 201, in addpackage
0.357     File "<string>", line 1, in <module>
0.357   ModuleNotFoundError: No module named '_distutils_hack'
0.357
0.357 Remainder of file ignored
2.703 WARNING: The directory '/home/seluser/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
3.151 Collecting pip
3.433   Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
3.680 Collecting setuptools
3.702   Downloading setuptools-75.4.0-py3-none-any.whl.metadata (6.8 kB)
3.738 Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
3.926    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.0 MB/s eta 0:00:00
3.952 Downloading setuptools-75.4.0-py3-none-any.whl (1.2 MB)
4.059    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 11.7 MB/s eta 0:00:00
4.100 Installing collected packages: setuptools, pip
4.740   Attempting uninstall: pip
4.744     Found existing installation: pip 24.0
4.988 error: uninstall-no-record-file
4.988
4.988 × Cannot uninstall pip 24.0
4.988 ╰─> The package's contents are unknown: no RECORD file was found for pip.
4.988
4.988 hint: The package was installed by debian. You should check if it can uninstall the package.
```

**Comment by SankaraNarayananK-sudo** [comment]
Additional debugging in Ubuntu

```
(seluser@566a4da28fe7:/$ curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
Error processing line 1 of /usr/lib/python3/dist-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 201, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Collecting setuptools
  Using cached setuptools-75.4.0-py3-none-any.whl.metadata (6.8 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Using cached setuptools-75.4.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, pip
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/seluser/.local/lib'
Check the permissions.)
```

**Comment by cnwikee** [comment]
Hi, I had the same problem, have you solved it yet?

**Comment by ichard26** [comment]
This is likely due to a change in Debian's pip packaging. You should use your distro's mechanism to upgrade pip, or alternatively set up a virtual environment in which you manage your own Python and pip.
