### ISSUE TITLE
Installing pip version 18.1 fails after latest commit change related to 19.0

### ISSUE THREAD

**Issue by kichalla** [pypa/get-pip#40]
I have been noticing the following error for couple of hours now and this seems to coincide with the latest commit that was pushed for 19.0: f2394e9ca6e16efb5f4020c4be4d12a557ac0533

```
2019-01-22T20:57:55.9413221Z + /usr/src/python/python /get-pip.py --prefix /opt/python/2.7.15 --disable-pip-version-check --no-cache-dir --no-warn-script-location pip==18.1
2019-01-22T20:57:57.4170626Z ‌DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.‌
2019-01-22T20:57:57.4657677Z ‌Collecting pip==18.1‌
2019-01-22T20:57:57.7992818Z   Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
2019-01-22T20:57:58.0449421Z Collecting setuptools
2019-01-22T20:57:58.5207209Z   Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl (573kB)
2019-01-22T20:57:58.5702104Z Collecting wheel
2019-01-22T20:57:58.6478810Z   Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
2019-01-22T20:57:58.6951558Z ‌Exception:‌
2019-01-22T20:57:58.6951840Z Traceback (most recent call last):
2019-01-22T20:57:58.6952035Z   File "/tmp/tmpuw2Nlo/pip.zip/pip/_internal/cli/base_command.py", line 176, in main
2019-01-22T20:57:58.6952244Z     status = self.run(options, args)
2019-01-22T20:57:58.6952471Z   File "/tmp/tmpuw2Nlo/pip.zip/pip/_internal/commands/install.py", line 346, in run
2019-01-22T20:57:58.6952678Z     session=session, autobuilding=True
2019-01-22T20:57:58.6952874Z   File "/tmp/tmpuw2Nlo/pip.zip/pip/_internal/wheel.py", line 848, in build
2019-01-22T20:57:58.6953070Z     assert building_is_possible
2019-01-22T20:57:58.6953218Z AssertionError
<
```

When I tried with the commit before the 19.0 change, it works fine. 

Please let me know if there's something I am missing. Thanks.

**Comment by nlighten** [comment]
Experiencing the same when building the standard python image from docker hub. When I omit the --no-cache-dir the build succeeds. 

Unfortunately the diff is too big to see what is going on.

**Comment by nlighten** [comment]
Related to https://github.com/pypa/pip/commit/7db266687cb6304b0708eb408c8f15efb78eedeb ??

**Comment by pradyunsg** [comment]
See pypa/pip#6158. pip 19.0.1 has been released with a fix and `get-pip.py` has been updated for the same.
