### ISSUE TITLE
Jython support

### ISSUE THREAD

**Issue by gagern** [pypa/get-pip#5]
I found that my Jython installation on Gentoo doesn't include pip, setuptools or any other similar packages. Resorting to `get-pip` I got an error message instead:

```
Traceback (most recent call last):
  File "get-pip.py", line 19154, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmp…/pip.zip/pip/__init__.py", line 15, in <module>
  File "/tmp/tmp…/pip.zip/pip/vcs/subversion.py", line 9, in <module>
  File "/tmp/tmp…/pip.zip/pip/index.py", line 30, in <module>
  File "/tmp/tmp…/pip.zip/pip/wheel.py", line 39, in <module>
  File "/tmp/tmp…/pip.zip/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/tmp/tmp…/pip.zip/pip/_vendor/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
```

I found that the official Jython installer will install pip and friends by default, so probably Gentoo is doing something strange here. Nevertheless, it would be nice if `get-pip` could deal with this in a reasonable way. By installing the module if possible, otherwise by suggesting users re-run the installer or something like that.

**Comment by pradyunsg** [comment]
I don't think this is feasible unless someone familiar with Jython helps out. I'm inclined to close this due to the lack of interest here.

**Comment by pradyunsg** [comment]
Closing as per pypa/pip#5121.
