### ISSUE TITLE
kali 2020 problem

### ISSUE THREAD

**Issue by 5l1v3r1** [pypa/get-pip#63]
python -m pip install --upgrade pip or pip2 install --upgrade pip gives me the same error
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "build/bdist.linux-x86_64/egg/OpenSSL/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/crypto.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/_util.py", line 152, in <module>
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode object

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this but this isn't the right place for this issue.

I think that Kali support forums would be better channels to get support for the issue you're facing. It *may* be reasonable to ask on [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [StackOverflow](https://stackoverflow.com), if asking on Kali support forums does not provide an answer.

**Comment by 5l1v3r1** [comment]
alright i fixed it, the problem was about openssl.
