### ISSUE TITLE
openWrt

### ISSUE THREAD

**Issue by zuosc** [pypa/get-pip#8]
hi,  I use Opkg install python3  in OpenWrt

when i use  python3 get-pip.py to install pip.   but it error.

My python3 files are  in   /media/AiCard_01/opt/lib/python3.5

the error is 

`Exception:
Traceback (most recent call last):
  File "/opt/lib/python3.5/distutils/sysconfig.py", line 422, in _init_posix
    parse_makefile(filename, g)
  File "/opt/lib/python3.5/distutils/sysconfig.py", line 291, in parse_makefile
    fp = TextFile(fn, strip_comments=1, skip_blanks=1, join_lines=1, errors="surrogateescape")
  File "/opt/lib/python3.5/distutils/text_file.py", line 100, in __init__
    self.open(filename)
  File "/opt/lib/python3.5/distutils/text_file.py", line 115, in open
    self.file = io.open(self.filename, 'r', errors=self.errors)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/lib/python3.5/config-3.5/Makefile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/wheel.py", line 242, in move_wheel_files
    name, user=user, home=home, root=root, isolated=isolated
  File "/opt/tmp/tmptkoregi1/pip.zip/pip/locations.py", line 192, in distutils_scheme
    i.finalize_options()
  File "/opt/lib/python3.5/distutils/command/install.py", line 283, in finalize_options
    (prefix, exec_prefix) = get_config_vars('prefix', 'exec_prefix')
  File "/opt/lib/python3.5/distutils/sysconfig.py", line 485, in get_config_vars
    func()
  File "/opt/lib/python3.5/distutils/sysconfig.py", line 428, in _init_posix
    raise DistutilsPlatformError(my_msg)
distutils.errors.DistutilsPlatformError: invalid Python installation: unable to open /opt/lib/python3.5/config-3.5/Makefile (No such file or directory)`

why is /opt/lib/python3.5/config-3.5/??

Can you  help me?

**Comment by pradyunsg** [comment]
Closing due to lack of activity. Hopefully you were able to figure this out! :)
