### ISSUE TITLE
SyntaxError: invalid syntax (last week was OK now KO)

### ISSUE THREAD

**Issue by digitalfredy** [pypa/get-pip#92]
To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
   * Centos 7

2. What is your Python version?
   * 2.7.5

3. What version of pip do you have?

   * None

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

   * https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py
   * Note: I'm using Vagrant with Ansible-local provider and they are using get-pip-py to install pip and Ansible

5. Could you describe your issue in as much detail as possible?

During the last month I was using Vagrant with Ansible-local provider to do some automated test and all was working without issues but today I did a `vagrant destroy` and them a `vagrant up` and the my new VM not be provisioned. It means can not install Ansible because can not install pip because it looks you did a change that introduces a bug in get-pip-py (it looks other people got same problem for python 3):

```
curl https://bootstrap.pypa.io/get-pip.py | sudo python

Stdout from the command:



Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0   894k      0  0:00:02  0:00:02 --:--:--  895k
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpL73OKo/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

When searching in duckduckgo I found that another person got same problem today but for Python 3.5: https://unix.stackexchange.com/questions/631244/why-does-get-pip-py-complain-about-invalid-syntax

**Comment by digitalfredy** [comment]
Closing because is same as #82
