### ISSUE TITLE
Install script throws an invalid syntax error so you cant install PIP

### ISSUE THREAD

**Issue by geraintp** [pypa/get-pip#94]
If you follow the instructions to install PIP using get-pip it falls over saying there's a syntax error on line 60.

```bash
curl https://bootstrap.pypa.io/get-pip.py | sudo python

Stdout from the command:



Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0   613k      0  0:00:03  0:00:03 --:--:--  613k
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpkHWg4q/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

os: Ubuntu 20.04
python: 2.7.18

**Comment by pradyunsg** [comment]
Use https://bootstrap.pypa.io/2.7/get-pip.py. See #82.
