### ISSUE TITLE
FileNotFoundError: [WinError 2] with LibreOffice_7.1.0_Win_x64

### ISSUE THREAD

**Issue by ReinRalle** [pypa/get-pip#98]
Hallo folks,

I using `get-pip.py (v21.0)` with `LibreOffice_7.0.4` without problems but 
now I'am testing `LibreOffice_7.1.0` and get some.

1. LibreOffice_7.0.4_Win_x64  (python-core-3.7.7)  => no problems  :-)
2. LibreOffice_7.1.0_Win_x64  (python-core-3.8.4)  => **FileNotFoundError: [WinError 2]**
<br>

    C:\Program Files\LibreOffice\program>python get-pip.py
    Traceback (most recent call last):
      File "get-pip.py", line 23974, in <module>
        main()
      File "get-pip.py", line 199, in main
        bootstrap(tmpdir=tmpdir)
      File "get-pip.py", line 177, in bootstrap
        sys.exit(pip_entry_point(args))
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\cli\main.py", line 60, in main
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\cli\main_parser.py", line 67, in parse_command
      File "C:\Program Files\LibreOffice\program\python-core-3.8.4\lib\optparse.py", line 1371, in parse_args
        values = self.get_default_values()
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\cli\parser.py", line 271, in get_default_values
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\configuration.py", line 138, in load
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\configuration.py", line 260, in _load_config_files
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\configuration.py", line 363, in iter_config_files
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\configuration.py", line 79, in get_configuration_files
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_internal\utils\appdirs.py", line 40, in site_config_dirs
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_vendor\appdirs.py", line 243, in site_config_dir
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_vendor\appdirs.py", line 138, in site_data_dir
      File "D:\SSD\EX\tmp\tmp905co5u3\pip.zip\pip\_vendor\appdirs.py", line 486, in _get_win_folder_from_registry
    FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
    
    C:\Program Files\LibreOffice\program>python

what can i do?

Thx

Ralf

**Comment by pradyunsg** [comment]
Hi!

Does your Python installation not have ctypes? I ask because you seem to be on Windows, and the following code block is the only reason that pip would ever try to fall back to `_get_win_folder_from_registry`.

```py
if system == "win32":
    try:
        from ctypes import windll
        _get_win_folder = _get_win_folder_with_ctypes
    except ImportError:
        try:
            import com.sun.jna
            _get_win_folder = _get_win_folder_with_jna
        except ImportError:
            _get_win_folder = _get_win_folder_from_registry
```

**Comment by ReinRalle** [comment]
Hi,

yes, that was the core problem. Already reported a bug report ([Bug 140236](https://bugs.documentfoundation.org/show_bug.cgi?id=140236)) to LibreOffice.

It was a problem with a missing DLL (libffi-7.dll).

The problem should be fixed in the next release. In the meantime I was able to help myself.

Thank you for your attention

Ralf
